//Used to replenish biomass in clonners, bioprinters etc
#define BIOMASS_TYPES list(/obj/item/weapon/reagent_containers/food/snacks/meat = 50 ,/obj/item/weapon/reagent_containers/food/snacks/meat/roachmeat= 40 ,/obj/item/weapon/reagent_containers/food/snacks/meat/xenomeat = 20)
//Basis of certain affect_blood calculations for stimulants.
#define STIM_TIME 3 SECONDS

//ID defines

//=Core
#define BLOOD "blood"
#define ANTIBODIES "antibodies"
#define WATER "water"
#define FUEL "fuel"

//=Dispenser reagents
#define ACETONE "acetone"
#define ALUMINUM "aluminum"
#define AMMONIA "ammonia"
#define CARBON "carbon"
#define COPPER "copper"
#define ETHANOL "ethanol"
#define HYDRAZINE "hydrazine"
#define IRON "iron"
#define LITHIUM "lithium"
#define MERCURY "mercury"
#define PHOSPHORUS "phosphorus"
#define POTASSIUM "potassium"
#define RADIUM "radium"
#define SACID "sacid"
#define HCLACID "hclacid"
#define SILICON "silicon"
#define SODIUM "sodium"
#define SULFUR "sulfur"
#define SUGAR "sugar"
#define TUNGSTEN "tungsten"

//=Narcotics
#define SPACEDRUGS "space_drugs"
#define SEROTROTIUM "serotrotium"
#define CRYPTOBIOLIN "cryptobiolin"
#define IMPEDREZENE "impedrezene"
#define MINDBREAKER "mindbreaker"
#define PSILOCYBIN "psilocybin"
#define NICOTINE "nicotine"
#define HYPERZINE "hyperzine"
#define SANGIUNUM "sangiunum"

//=Medicine
#define INAPROVALINE "inaprovaline"
#define BICARIDINE "bicaridine"
#define MERALYNE "meralyne"
#define KELOTANE "kelotane"
#define DERMALINE "dermaline"
#define DYLOVENE "anti_toxin"
#define DEXALIN "dexalin"
#define DEXPLUS "dexalinp"
#define TRICORDRAZINE "tricordrazine"
#define CRYOXADONE "cryoxadone"
#define CLONEXADONE "clonexadone"
#define PARACETAMOL "paracetamol"
#define TRAMADOL "tramadol"
#define OXYCODONE "oxycodone"
#define SYNAPTIZINE "synaptizine"
#define ALKYSINE "alkysine"
#define IMIDAZOLINE "imidazoline"
#define PERIDAXON "peridaxon"
#define RYETALYN "ryetalyn"
#define NEGATIVELING "negativeling"
#define POSITIVELING "positiveling"
#define ETHYLREDOXRAZINE "ethylredoxrazine"
#define HYRONALIN "hyronalin"
#define ARITHRAZINE "arithrazine"
#define SPACEACILLIN "spaceacillin"
#define STERILIZINE "sterilizine"
#define LEPORAZINE "leporazine"
#define METHYLPHENIDATE "methylphenidate"
#define CITALOPRAM "citalopram"
#define PAROXETINE "paroxetine"
#define REZADONE "rezadone"
#define QUICKCLOT "quickclot"
#define OSSISINE "ossisine"
#define NOEXCUTITE "noexcutite"
#define KYPHOTORIN "kyphotorin"
#define POLYSTEM "polystem"
#define DETOX "detox"
#define PURGER "purger"
#define ADDICTOL "addictol"
#define AMINAZINE "aminazine"
#define HALOPERIDOL "haloperidol"
#define VOMITOL "vomitol"

//=Nanites
#define NANITEBASE "nanites"
#define DEADNANITE "nanodead"
#define UNCAPNANITE "uncap nanites"
#define ARADNANITE "arad nanites"
#define IMPLNANITE "implant nanites"
#define NANTIDOTE "nantidotes"
#define NANOSYMB "nanosymbiotes"
#define OXYNANITE "oxyrush"
#define TCSNANITE "trauma_control_system"
#define PURGNANITE "nanopurgers"
#define CBUNANITE "cbu"
#define CBCNANITE "cbc"
#define VOICENANITE "nanovoice"
#define HANDNANITE "nanohands"